import { useState, useCallback } from 'react';
import { useWebContainer } from './useWebContainer';
import logger from '@/lib/logger';

export function useFiles(initialSessionId: string = '') {
  const [files, setFiles] = useState<Record<string, string>>({});
  const [activeFile, setActiveFile] = useState<string>('');
  const [sessionId, setSessionId] = useState<string>(initialSessionId);
  const { webcontainer } = useWebContainer();

  // Write a single file to both React state and WebContainer FS
  const updateFile = useCallback(async (path: string, content: string) => {
      const cleanPath = path.startsWith('/') ? path.substring(1) : path;

      // Update local state for UI
      setFiles(prev => ({ ...prev, [cleanPath]: content }));

      // Write directly to WebContainer file system
      if (webcontainer) {
          try {
              const parts = cleanPath.split('/');
              if (parts.length > 1) {
                  const dir = parts.slice(0, -1).join('/');
                  await webcontainer.fs.mkdir(dir, { recursive: true });
              }
              await webcontainer.fs.writeFile(cleanPath, content);
          } catch (err) {
              logger.error('[useFiles] Failed to write file to WebContainer:', cleanPath, err);
          }
      }
  }, [webcontainer]);

  // Recursively read all files from WebContainer FS
  const readDirectoryRecursive = useCallback(async (
    dirPath: string,
    result: Record<string, string>
  ): Promise<void> => {
    if (!webcontainer) return;

    try {
      const entries = await webcontainer.fs.readdir(dirPath, { withFileTypes: true });
      for (const entry of entries) {
        const entryPath = dirPath ? `${dirPath}/${entry.name}` : entry.name;

        // Skip node_modules, .git, hidden directories, and system config files
        if (entry.name === 'node_modules' || entry.name === '.git' || entry.name === '.cache') {
          continue;
        }

        // Skip system config files written by useDevServer at the root level
        if (!dirPath && (entry.name === '.npmrc' || entry.name === '.env')) {
          continue;
        }

        // Skip lock files generated by npm install inside WebContainer
        if (entry.name === 'package-lock.json' || entry.name === 'yarn.lock' || entry.name === 'pnpm-lock.yaml') {
          continue;
        }

        if (entry.isDirectory()) {
          await readDirectoryRecursive(entryPath, result);
        } else if (entry.isFile()) {
          try {
            const content = await webcontainer.fs.readFile(entryPath, 'utf-8');
            result[entryPath] = content;
          } catch (readErr) {
            logger.warn('[useFiles] Failed to read file:', entryPath, readErr);
          }
        }
      }
    } catch (err) {
      logger.error('[useFiles] Failed to read directory:', dirPath, err);
    }
  }, [webcontainer]);

  // Load all files from WebContainer FS (replaces old /api/files backend call)
  const loadAllFiles = useCallback(async (_sessionId?: string) => {
    if (!webcontainer) {
      logger.warn('[useFiles] WebContainer not ready, skipping loadAllFiles');
      return;
    }

    const fileContents: Record<string, string> = {};
    await readDirectoryRecursive('', fileContents);

    const filePaths = Object.keys(fileContents);

    setFiles(fileContents);

    // Auto-select first file if none is active
    if (filePaths.length > 0 && !activeFile) {
      setActiveFile(filePaths[0]);
    }
  }, [webcontainer, readDirectoryRecursive, activeFile]);

  // Delete a file or directory from both React state and WebContainer FS
  const deleteFile = useCallback(async (path: string) => {
    const cleanPath = path.startsWith('/') ? path.substring(1) : path;

    // Remove from local state (handle both files and directories)
    setFiles(prev => {
      const next: Record<string, string> = {};
      for (const [filePath, content] of Object.entries(prev)) {
        // Skip exact match or any file under this directory
        if (filePath === cleanPath || filePath.startsWith(cleanPath + '/')) {
          continue;
        }
        next[filePath] = content;
      }
      return next;
    });

    // Clear active file if it was deleted
    setActiveFile(prev => {
      if (prev === cleanPath || prev.startsWith(cleanPath + '/')) {
        return '';
      }
      return prev;
    });

    // Remove from WebContainer FS
    if (webcontainer) {
      try {
        await webcontainer.fs.rm(cleanPath, { recursive: true });
      } catch (err) {
        logger.error('[useFiles] Failed to delete from WebContainer:', cleanPath, err);
      }
    }
  }, [webcontainer]);

  // Rename a file or directory
  const renameFile = useCallback(async (oldPath: string, newPath: string) => {
    const cleanOldPath = oldPath.startsWith('/') ? oldPath.substring(1) : oldPath;
    const cleanNewPath = newPath.startsWith('/') ? newPath.substring(1) : newPath;

    // Update local state: move all files under oldPath to newPath
    setFiles(prev => {
      const next: Record<string, string> = {};
      for (const [filePath, content] of Object.entries(prev)) {
        if (filePath === cleanOldPath) {
          next[cleanNewPath] = content;
        } else if (filePath.startsWith(cleanOldPath + '/')) {
          const relativePart = filePath.substring(cleanOldPath.length);
          next[cleanNewPath + relativePart] = content;
        } else {
          next[filePath] = content;
        }
      }
      return next;
    });

    // Update active file if it was renamed
    setActiveFile(prev => {
      if (prev === cleanOldPath) return cleanNewPath;
      if (prev.startsWith(cleanOldPath + '/')) {
        return cleanNewPath + prev.substring(cleanOldPath.length);
      }
      return prev;
    });

    // Rename in WebContainer FS (read → write new → delete old)
    if (webcontainer) {
      try {
        // Check if it's a file or directory by trying to read it
        const isDirectory = await webcontainer.fs.readdir(cleanOldPath, { withFileTypes: true })
          .then(() => true)
          .catch(() => false);

        if (isDirectory) {
          // For directories, recursively copy contents then delete old
          const copyRecursive = async (srcDir: string, destDir: string) => {
            await webcontainer.fs.mkdir(destDir, { recursive: true });
            const entries = await webcontainer.fs.readdir(srcDir, { withFileTypes: true });
            for (const entry of entries) {
              const srcPath = `${srcDir}/${entry.name}`;
              const destPath = `${destDir}/${entry.name}`;
              if (entry.isDirectory()) {
                await copyRecursive(srcPath, destPath);
              } else {
                const content = await webcontainer.fs.readFile(srcPath, 'utf-8');
                await webcontainer.fs.writeFile(destPath, content);
              }
            }
          };
          await copyRecursive(cleanOldPath, cleanNewPath);
        } else {
          // For files, read content → create parent dir → write new → delete old
          const content = await webcontainer.fs.readFile(cleanOldPath, 'utf-8');
          const newParts = cleanNewPath.split('/');
          if (newParts.length > 1) {
            await webcontainer.fs.mkdir(newParts.slice(0, -1).join('/'), { recursive: true });
          }
          await webcontainer.fs.writeFile(cleanNewPath, content);
        }
        await webcontainer.fs.rm(cleanOldPath, { recursive: true });
      } catch (err) {
        logger.error('[useFiles] Failed to rename in WebContainer:', err);
      }
    }
  }, [webcontainer]);

  // Create an empty directory in both React state and WebContainer FS
  const createFolder = useCallback(async (path: string) => {
    const cleanPath = path.startsWith('/') ? path.substring(1) : path;

    // Add a placeholder entry so the folder appears in the file tree
    // We use a convention: folders are tracked by having at least one file inside
    // But for empty folders, we need to create them in WebContainer FS
    if (webcontainer) {
      try {
        await webcontainer.fs.mkdir(cleanPath, { recursive: true });
      } catch (err) {
        logger.error('[useFiles] Failed to create folder in WebContainer:', cleanPath, err);
      }
    }
  }, [webcontainer]);

  return {
    files,
    setFiles,
    activeFile,
    setActiveFile,
    sessionId,
    setSessionId,
    loadAllFiles,
    updateFile,
    deleteFile,
    renameFile,
    createFolder
  };
}
